In [1]:
from IPython.display import display, Math, Latex

import pandas as pd
import numpy as np
import numpy_financial as npf
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime
import threading

## Group Assignment
### Team Number: 11
### Team Member Names: Bob Li, Lucas Zaharia, Charles Chen
### Team Strategy Chosen: RISKY

In [2]:

file_name="Tickers_Example.csv"
# Read the File to a pd dataframe
ticker_list=pd.read_csv(file_name,header=None)

In [3]:
# Assign Start and End date for the analysis
start_date="2022-11-01"
end_date= "2022-12-30"

# Determine the minimum number of trading days required to be considered
apple =yf.Ticker("AAPL")
apple_hist = apple.history(start= start_date, end= end_date)
apple_hist.dropna(inplace=True)
min_data_len = len(apple_hist.index)

In [4]:
# Extract first trading day
apple_hist.reset_index(inplace=True)
first_trading_day = str(apple_hist["Date"][0])
first_trading_day = first_trading_day[0:10]

In [5]:
# add_month produces the trading volume in a given month and if the month has at least
# 20 trading days

# add_month: yf.Ticker Str Str -> [Monthly Volume, 0 or 1]
def add_month(ticker, start_here, end_here):
    # Create var called month_num representing if the month is eligible for calculation
    month_num=0
    
    # Get the history of month
    hist=ticker.history(start= start_here, end= end_here)
    
    # get a dataframe of volume
    company=hist["Volume"]
    
    # requires at least 20 trading days to be considered in the average
    if len(company) >= 20:
        # Calculate Sum
        month=company.sum()
        month_num+=1
    else:
        # Or do not add the month in
        month=0
    return [month, month_num]

# Calculate the Monthly Average of Volume of a stock
# Take in a ticker and returns monthly Average of that ticker
def monthly_avg(ticker):
    # Start variable total
    total=0
    
    # Start variable month_num representing the number of months
    month_num=0
    
    # Adding the volume for Jan-Sept
    for i in range(1,9):
        total+=add_month(ticker,f'2022-0{i}-01',f'2022-0{i+1}-01')[0]
        month_num+=add_month(ticker,f'2022-0{i}-01',f'2022-0{i+1}-01')[1]
    
    # Adding the volume for Sept-Oct
    total+=add_month(ticker,f'2022-09-01',f'2022-10-01')[0]
    month_num+=add_month(ticker,f'2022-09-01',f'2022-10-01')[1]
    
    total+=add_month(ticker,f'2022-10-01',f'2022-11-01')[0]
    month_num+=add_month(ticker,f'2022-10-01',f'2022-11-01')[1]
    
    # Calculating the monthly Average
    month_avg=total/month_num
    return month_avg
    

# Take in a dataframe of ticker name and an index (i)
# Function edits the indexed ticker name in the dataframe (remove it when it does not meet requirements)
def check_ticker_valid(i, ticker_list): 
    # Find indexed ticker name
    ticker=ticker_list.iloc[i,0]
    
    # Create the yfinance ticker
    company=yf.Ticker(ticker)
    
    # Use try except method to catch errors
    try:
        # Get the market of the ticker
        location=company.info['market']

        # Call monthly_avg to get the monthly average volume
        avg=monthly_avg(company)
        
        # calculate the length of data range
        company_hist = company.history(start= start_date, end= end_date)
        company_hist.dropna(inplace=True)
        lenn = len(company_hist.index)

        # To be eligible the stock must:
        #  - Be in US market
        #  - Have average monthly volume >=200000
        #  - Not an index
        #  - Has a certain number of trading days within time period (our requirement)
        if location != 'us_market' or avg < 200000 or lenn< min_data_len or "^" == ticker[0]:
            # Remove the Ticker from list if it does not meet requirements
            ticker_list.iloc[i,0]="N/A"
       
    except:
        # Remove the Ticker from list if it does not meet requirements
        ticker_list.iloc[i,0]="N/A"

In [6]:
# Create a list of threads
threads = []

# Start Threading in a loop
for i in range(0,len(ticker_list)):
    # Create a new thread
    t = threading.Thread(target=check_ticker_valid, args=[i, ticker_list])
    
    # Start thread
    t.start()
    
    # Add thread to thread list
    threads.append(t)

# Stop all threads in list
for thread in threads:
    thread.join()

- TWX: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted- PCLN: No data found for this date range, symbol may be delisted

- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted- PCLN: No data found for this date range, symbol may be delisted

- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted
- PCLN: No data found for this date range, symbol may be delisted
- TWX: No data found for this date range, symbol may be delisted- PCLN: No data found for this date range, symbol may be delisted

## Note on above code block

### You may see that there are outputs saying that certain tickers may be delisted. This is expected and normal. Yahoo Finance does this automatically. You may also notice that there are multiple delisted messages for the same ticker. Please note that this is not because we are retrieving the same data multiple times from the same ticker. This is because we use threading to split up calculating monthly volume, so when we call Yahoo Finance on each month, we get the same delisted message.

In [7]:
# Remove empty entries
ticker_list=ticker_list.replace('N/A',np.NaN)
ticker_list=ticker_list.dropna()

# Reset index
ticker_list.reset_index(drop=True, inplace=True)

In [8]:
# Create empty column called score
ticker_list['score']=''

# Calculates and insert score for each ticker in the dataframe
# Consumes Ticker list dataframe, index, start and end date
def eval_ticker(ticker_list,i,start_date, end_date):
    ticker_name=ticker_list.iloc[i,0]
    ticker=yf.Ticker(ticker_name)
    company=ticker.history(start= start_date, end= end_date)
    company=company["Close"]
    company=company.pct_change()
    company=company.dropna()
    standard_deviation=company.std()
    score=standard_deviation
    ticker_list['score'][i]=score

        0 score
0    AAPL
1    ABBV
2     ABT
3     ACN
4     AIG
5    AMZN
6     AXP
7      BA
8     BAC
9    BIIB
10     BK
11    BLK
12    BMY
13      C
14    CAT
15     CL
16  CMCSA
17    COF
18    COP
19   COST
20   CSCO
21    CVS
22     GM
23   GOOG
24    JPM
25    KMI
26     KO
27    LLY
28    LMT
29     MO
30    MON
31    MRK
32     MS
33   MSFT
34    NEE
35    NKE
36   ORCL
37    OXY
38    PEP
39    PFE
40     PG
41     PM
42   PYPL
43   QCOM
44   SBUX
45    SLB
46     SO
47    SPG
48      T
49    TGT
50    TXN
51    UNH
52    UNP
53    UPS
54    USB

In [9]:

##Creat a list of threads
threads = []
##Start Threading in a loop
for i in range(0,len(ticker_list)):
    ##Create a new thread
    t = threading.Thread(target=eval_ticker, args=[ticker_list,i,start_date, end_date])
    ##Start thread
    t.start()
    ##Add thread to thread list
    threads.append(t)
##Stop all thread in list
for thread in threads:
    thread.join()

In [10]:
def print_exchange(i, ticker_list):
    ticker=ticker_list.iloc[i,0]
    ticker=yf.Ticker(ticker)


##Creat a list of threads
threads = []
##Start Threading in a loop
for i in range(0,len(ticker_list)):
    ##Create a new thread
    t = threading.Thread(target=print_exchange, args=[i, ticker_list])
    ##Start thread
    t.start()
    ##Add thread to thread list
    threads.append(t)
##Stop all thread in list
for thread in threads:
    thread.join()

NYQ
NYQ
NYQ
NYQ
NCMNYQ

NYQ
NYQ
NYQ
NMS
NMS
NMS
NYQ
NYQ
NMS
NYQNMS
NMS

NYQ
NYQNYQ

NYQNMS

NYQ
NMS
NYQ
NYQ
NYQ
NYQ
NMS
NYQ
NYQ
NYQ
NYQ
NMS
NYQ
NYQ
NYQ
NYQ
NYQ
NYQ
NMS
NYQNYQ

NYQ
NMS
NYQ
NYQ
NMS
NYQ
NYQ
NYQ
NYQ
NYQ
NYQ

In [11]:
##Sorte the dataframe by score in decreasing order
ticker_list.sort_values(by=['score'], ascending=False,inplace=True)
##Reset the index
ticker_list.reset_index(drop=True,inplace=True)
ticker_list

        0     score
0     TGT  0.048245
1     COF   0.04517
2    PYPL  0.040782
3    QCOM  0.040264
4    AMZN  0.040111
5     BLK  0.039472
6     OXY   0.03742
7     NKE  0.033806
8     COP  0.032092
9    AAPL  0.030343
10   GOOG  0.029878
11    ACN  0.028725
12   MSFT  0.027858
13   SBUX  0.026645
14    SPG   0.02433
15    TXN   0.02429
16      C  0.024264
17    AXP  0.024001
18     GM  0.023711
19     BA   0.02347
20    SLB  0.023244
21    UPS  0.022162
22   CSCO  0.020529
23    NEE  0.020175
24    UNP  0.019641
25     MS  0.019229
26    UNH  0.018948
27    USB  0.018916
28  CMCSA    0.0186
29    KMI  0.018335
30   COST   0.01783
31    LMT  0.017202
32    LLY  0.016958
33    CAT  0.016879
34    ABT  0.016255
35     BK  0.015928
36    CVS  0.015258
37    MRK  0.015172
38     SO  0.014972
39    BAC  0.014839
40    JPM  0.014415
41    PFE  0.013831
42    BMY  0.013694
43     PM  0.013471
44   ORCL  0.012951
45   BIIB  0.012869
46     MO  0.012309
47    AIG  0.012006
48     PG  0.011906
49     KO  0.011809
50    PEP  0.010779
51   ABBV  0.010278
52     CL  0.009567
53      T  0.009475
54    MON   0.00075

In [12]:
# Generates a dictionary where the key is the stock ticker and the associated value
# is a DataFrame containing daily close prices
# Parameters:
#  - ticker_lst (List): List containing stock tickers
# Returns:
#  - df_dict (Dictionary): Dictionary containing stock prices
def generate_stock_df_dict(ticker_lst):
    # Variables
    start_date = "2022-10-01"
    hist_interval = "1d"  
    df_dict = {}
    
    # Loop through each ticker in ticker_lst
    for ticker in ticker_lst:
        stock = yf.Ticker(ticker)
        
        # Get stock prices
        stock_hist = stock.history(start=start_date, interval=hist_interval)
        
        # Drop empty rows
        stock_hist.dropna(inplace=True)
        
        # Add DF with just Close column to dict
        df_dict[ticker] = stock_hist[["Close"]]
        
    # Return dict
    return df_dict

# Finds correlation in expected returns between two stocks when given a dictionary
# containing their stock prices.
# Parameters:
#  - ticker (String): Ticker of first stock
#  - second_ticker (String): Ticker of second stock
#  - df_dict (Dictionary): Dictionary containing stock prices
# Returns:
#  - returns_corr (Float): Correlation between expected returns
def find_corr(ticker, second_ticker, df_dict):
    # Variables
    ls = "_" + ticker
    rs = "_" + second_ticker
    
    # Join the price DataFrames for the two stocks
    prices = df_dict[ticker].join(df_dict[second_ticker], lsuffix=ls, rsuffix=rs)
    
    # Drop empty rows
    prices.dropna(inplace=True)
    
    # Get daily returns and drop first row
    daily_returns = prices.pct_change()
    daily_returns = daily_returns.iloc[1:]
    
    # Extract correlation
    returns_corr = daily_returns.corr().iloc[0, 1]
    
    # Return correlation
    return returns_corr

# Generates a list of portfolios, where each portfolio is composed of the 11 most
# correlated stocks to each stock in ticker_lst as well as the stock in ticker_lst
# Parameters:
#  - ticker_lst (List): List of tickers with length of at least 12
#  - df_dict (Dictionary): Dictionary containing stock prices
# Returns:
#  - portfolios (2D List): List of portfolios
def generate_portfolios(ticker_lst, df_dict):
    # Create empty list
    portfolios = []
    
    # Loop through each ticker in ticker_lst
    for ticker in ticker_lst:
        # Copy ticker_lst to avoid reference problems
        ticker_lst_copy = ticker_lst.copy()
        
        # Remove current ticker from copy
        ticker_lst_copy.remove(ticker)
        
        # Create a new DF where the index is ticker_lst_copy
        corr_df = pd.DataFrame(index=ticker_lst_copy)
        
        # Name the index Stock
        corr_df.index.name = "Stock"
        
        # Create a new column called Corr where each value is initially -2
        corr_df["Corr"] = -2
        
        # Loop through each ticker in ticker_lst_copy
        for second_ticker in ticker_lst_copy:
            # Find correlation between tickers in outer and inner for loops
            corr = find_corr(ticker, second_ticker, df_dict)
            
            # Place correlation value in appropriate location in DF
            corr_df.loc[second_ticker, "Corr"] = corr
        
        # Reset index
        corr_df.reset_index(inplace=True)
        
        # Sort DF values by Corr column from most correlated to least correlated
        corr_df.sort_values(by="Corr", ascending=False, inplace=True)
        
        # Create a new one element list containing ticker in outer for loop
        current_portfolio = [ticker]
        
        # Extract 11 most correlated stocks as a list
        additional_stocks = list(corr_df.head(11).Stock)
        
        # Extend the one element list to have the correlated stocks
        current_portfolio.extend(additional_stocks)
        
        # Append current portfolio to list of portfolios
        portfolios.append(current_portfolio)
    
    # Return list of portfolios
    return portfolios

In [13]:
ticker_list = ticker_list.head(25)
risky_tickers = list(ticker_list[0])

stock_price_dict = generate_stock_df_dict(risky_tickers)

portfolios = generate_portfolios(risky_tickers, stock_price_dict)
portfolios

[['TGT',
  'UPS',
  'GM',
  'PYPL',
  'SPG',
  'TXN',
  'NKE',
  'AMZN',
  'QCOM',
  'AAPL',
  'BLK',
  'CSCO'],
 ['COF',
  'BLK',
  'AXP',
  'C',
  'ACN',
  'MSFT',
  'AAPL',
  'TXN',
  'NKE',
  'SPG',
  'UNP',
  'UPS'],
 ['PYPL',
  'AMZN',
  'QCOM',
  'AXP',
  'BLK',
  'ACN',
  'NKE',
  'AAPL',
  'TXN',
  'MSFT',
  'GM',
  'C'],
 ['QCOM',
  'ACN',
  'TXN',
  'AAPL',
  'MSFT',
  'CSCO',
  'PYPL',
  'BLK',
  'GOOG',
  'C',
  'AXP',
  'UPS'],
 ['AMZN',
  'PYPL',
  'UPS',
  'MSFT',
  'GOOG',
  'ACN',
  'BLK',
  'NKE',
  'TXN',
  'AAPL',
  'AXP',
  'C'],
 ['BLK',
  'C',
  'COF',
  'ACN',
  'AXP',
  'MSFT',
  'UPS',
  'TXN',
  'AAPL',
  'SPG',
  'QCOM',
  'PYPL'],
 ['OXY',
  'COP',
  'SLB',
  'GM',
  'TXN',
  'UPS',
  'C',
  'QCOM',
  'PYPL',
  'NKE',
  'BLK',
  'SPG'],
 ['NKE',
  'SBUX',
  'TXN',
  'AAPL',
  'SPG',
  'UPS',
  'BLK',
  'C',
  'PYPL',
  'AXP',
  'COF',
  'AMZN'],
 ['COP',
  'OXY',
  'SLB',
  'TGT',
  'UPS',
  'GM',
  'TXN',
  'SPG',
  'BLK',
  'C',
  'PYPL',
  'NKE'],
 ['AAPL',
  'ACN',
  'MSFT',
  'QCOM',
  'TXN',
  'GOOG',
  'BLK',
  'CSCO',
  'AXP',
  'COF',
  'NKE',
  'UPS'],
 ['GOOG',
  'MSFT',
  'AAPL',
  'ACN',
  'TXN',
  'AMZN',
  'QCOM',
  'AXP',
  'NKE',
  'BLK',
  'PYPL',
  'COF'],
 ['ACN',
  'AAPL',
  'QCOM',
  'MSFT',
  'BLK',
  'AXP',
  'TXN',
  'C',
  'COF',
  'UPS',
  'GOOG',
  'CSCO'],
 ['MSFT',
  'GOOG',
  'TXN',
  'ACN',
  'AAPL',
  'BLK',
  'QCOM',
  'AXP',
  'COF',
  'AMZN',
  'C',
  'CSCO'],
 ['SBUX',
  'NKE',
  'AXP',
  'TXN',
  'BLK',
  'C',
  'COF',
  'MSFT',
  'QCOM',
  'ACN',
  'UPS',
  'SPG'],
 ['SPG',
  'GM',
  'BLK',
  'NKE',
  'UPS',
  'TXN',
  'C',
  'COF',
  'CSCO',
  'ACN',
  'AXP',
  'MSFT'],
 ['TXN',
  'MSFT',
  'QCOM',
  'AAPL',
  'ACN',
  'BLK',
  'NKE',
  'GOOG',
  'CSCO',
  'UPS',
  'C',
  'SPG'],
 ['C',
  'BLK',
  'COF',
  'UPS',
  'ACN',
  'GM',
  'AXP',
  'MSFT',
  'QCOM',
  'TXN',
  'AAPL',
  'NKE'],
 ['AXP',
  'COF',
  'ACN',
  'BLK',
  'MSFT',
  'AAPL',
  'C',
  'PYPL',
  'QCOM',
  'GOOG',
  'UPS',
  'TXN'],
 ['GM',
  'C',
  'SPG',
  'UPS',
  'BLK',
  'PYPL',
  'TGT',
  'COF',
  'ACN',
  'TXN',
  'NKE',
  'QCOM'],
 ['BA',
  'MSFT',
  'GOOG',
  'SPG',
  'BLK',
  'TXN',
  'NEE',
  'AXP',
  'PYPL',
  'C',
  'GM',
  'COF'],
 ['SLB',
  'OXY',
  'COP',
  'TXN',
  'AMZN',
  'UPS',
  'QCOM',
  'GM',
  'C',
  'TGT',
  'BLK',
  'MSFT'],
 ['UPS',
  'C',
  'BLK',
  'ACN',
  'GM',
  'AMZN',
  'TXN',
  'AAPL',
  'NKE',
  'SPG',
  'AXP',
  'TGT'],
 ['CSCO',
  'AAPL',
  'QCOM',
  'TXN',
  'ACN',
  'MSFT',
  'BLK',
  'AXP',
  'SPG',
  'C',
  'GM',
  'UPS'],
 ['NEE',
  'BLK',
  'UNP',
  'AXP',
  'ACN',
  'AAPL',
  'NKE',
  'COF',
  'MSFT',
  'SPG',
  'UPS',
  'C'],
 ['UNP',
  'NEE',
  'BLK',
  'COF',
  'C',
  'AXP',
  'UPS',
  'ACN',
  'NKE',
  'MSFT',
  'SBUX',
  'AAPL']]

In [14]:
portfolio_stds = []

# Builds a portfolio with $500000 and adds the standard deviation of the portfolio to portfolio_stds
# Parameters: A list of 12 tickers
def buildportfolio(lst):
    portfolio = pd.DataFrame()
    
    #Determines how much of the portfolio the stock will be worth, based on its position in the list
    for x in range(len(lst)):
        if x <= 1:
            investment = 125000
        elif x == 2:
            investment = 62500
        else:
            investment = 62500/3
        
        #Gets closing price value from the dictionary defined earlier
        portfolio[lst[x]] = stock_price_dict[lst[x]]
        
        #Defines the number of shares based on the stock price from the first day
        try:
            num_shares = investment / portfolio.loc[first_trading_day, lst[x]]
        except:
            num_shares = investment / portfolio.loc["2022-11-01", lst[x]]
        
        #Multiplies closing value by number of shares 
        portfolio[lst[x]] = portfolio[lst[x]] * num_shares
        
    #Drops NaN values
    portfolio = portfolio.dropna()
    
    #Adds all stocks into a final column to track the portfolio value over time
    portfolio["portfolio value"] = portfolio.sum(axis = 1)
    
    #Adds the standard deviation of the portfolio to the portfolio_stds
    portfolio_stds.append(portfolio['portfolio value'].std())
    
#Applys buildportfolio to every list of tickers in portfolios
for n in portfolios:
    buildportfolio(n)

In [15]:
#Gets the list of tickers from portfolios based on the position of the largest standard deviation in portfolio_stds, since order is preserved
finalport_tickerslst = portfolios[portfolio_stds.index(max(portfolio_stds))]

finalport_pricelst = []

# Defines finalport_pricelst as the price of each ticker at the required date
for i in range(len(finalport_tickerslst)):
    finalport_pricelst.append(stock_price_dict[finalport_tickerslst[i]].loc["2022-11-23", "Close"])
    
finalport_shareslst = []

#Defines finalport_shareslst as the number of shares of each stock, based on finalport_pricelst and the position of the ticker in the finalport_tickerslst
for n in range(len(finalport_tickerslst)):
    value = -1
    if n <= 1:
        value = 125000
    elif n == 2:
        value = 62500
    else:
        value = 62500/3
    finalport_shareslst.append(value/finalport_pricelst[n])
    
#Creates a dictionary with the data above
finalport = { "Ticker" : finalport_tickerslst,
            "Price" : finalport_pricelst,
            "Shares" : finalport_shareslst}

#Creates the index for the portfolio
index_list = list(range(1, 13))

#Creates the dataframe from the data in finalport
Portfolio_Final = pd.DataFrame(finalport, index=index_list)

#Adds a column for Value using price * shares
Portfolio_Final["Value"] = Portfolio_Final.Price * Portfolio_Final.Shares

#Adds a column for Weight based oln the value of each stock
Portfolio_Final["Weight"] = Portfolio_Final.Value / 500000 * 100

Portfolio_Final

   Ticker       Price       Shares          Value     Weight
1     SPG  119.610001  1045.063116  125000.000000  25.000000
2      GM   40.110001  3116.429771  125000.000000  25.000000
3     BLK  736.320007    84.881572   62500.000000  12.500000
4     NKE  106.650002   195.343020   20833.333333   4.166667
5     UPS  182.839996   113.942976   20833.333333   4.166667
6     TXN  178.979996   116.400345   20833.333333   4.166667
7       C   48.240002   431.868421   20833.333333   4.166667
8     COF  101.629997   204.991970   20833.333333   4.166667
9    CSCO   48.570000   428.934187   20833.333333   4.166667
10    ACN  294.529999    70.734164   20833.333333   4.166667
11    AXP  153.929993   135.342911   20833.333333   4.166667
12   MSFT  247.580002    84.147884   20833.333333   4.166667

In [16]:
print("Total Value:", Portfolio_Final.Value.sum())
print("Total Weight:", Portfolio_Final.Weight.sum())

Total Value: 499999.9999999999
Total Weight: 100.0

In [17]:
#Creates another dataframe using only the Ticker and Shares column from Portfolio_Final
Stocks_Final = Portfolio_Final[["Ticker", "Shares"]]

#Exports the dataframe to a csv file
Stocks_Final.to_csv('Stocks_Group_11.csv')

## Contribution Declaration

The following team members made a meaningful contribution to this assignment:

Bob Li  
Lucas Zaharia  
Charles Chen